package com.notesshared.servlet;
import com.notesshared.dao.*;import com.notesshared.model.User;import com.notesshared.util.*;import jakarta.servlet.*;import jakarta.servlet.annotation.WebServlet;import jakarta.servlet.http.*;import java.io.*;import java.sql.*;
@WebServlet({"/login","/logout","/register/admin","/register/student","/register/supervisor","/admin/approval"})
public class AuthServlet extends HttpServlet{
 private final UserDao users=new UserDao();private final CollegeDao colleges=new CollegeDao();private final CourseDao courses=new CourseDao();
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{try{switch(r.getServletPath()){case "/login"->login(r,s);case "/logout"->logout(r,s);case "/register/admin"->registerAdmin(r,s);case "/register/student"->registerStudent(r,s);case "/register/supervisor"->registerSupervisor(r,s);case "/admin/approval"->approval(r,s);default->s.sendError(404);}}catch(IllegalArgumentException e){r.setAttribute("error",e.getMessage());r.getRequestDispatcher("/error.jsp").forward(r,s);}catch(SQLException e){r.setAttribute("error",friendly(e));r.getRequestDispatcher("/error.jsp").forward(r,s);}}
 private void login(HttpServletRequest r,HttpServletResponse s)throws SQLException,IOException{String email=norm(r.getParameter("email")),pass=r.getParameter("password");User u=email==null?null:users.findByEmail(email);if(u==null||!PasswordUtil.verify(pass==null?"":pass,u.getPasswordHash())){s.sendRedirect(r.getContextPath()+"/login.jsp?error=Invalid+email+or+password");return;}if(!"APPROVED".equals(u.getApprovalStatus())){s.sendRedirect(r.getContextPath()+"/login.jsp?error=Your+account+is+"+u.getApprovalStatus().toLowerCase()+".+Wait+for+college+admin+approval.");return;}HttpSession h=r.getSession(false);if(h!=null)h.invalidate();h=r.getSession(true);h.setAttribute("userId",u.getId());h.setAttribute("role",u.getRole());h.setAttribute("collegeId",u.getCollegeId());h.setAttribute("courseId",u.getCourseId());h.setAttribute("userName",u.getName());s.sendRedirect(r.getContextPath()+"/app");}
 private void logout(HttpServletRequest r,HttpServletResponse s)throws IOException{HttpSession h=r.getSession(false);if(h!=null)h.invalidate();s.sendRedirect(r.getContextPath()+"/login.jsp?message=Logged+out");}
 private void registerAdmin(HttpServletRequest r,HttpServletResponse s)throws SQLException,IOException{String n=r.getParameter("collegeName"),e=norm(r.getParameter("email")),p=r.getParameter("password");req(n,"College name is required.");req(e,"College email is required.");req(p,"Password is required.");if(p.length()<8)throw new IllegalArgumentException("Password must be at least 8 characters.");try(Connection c=Db.getConnection()){c.setAutoCommit(false);try{int id=colleges.create(c,n.trim(),e);users.createAdmin(c,id,n.trim(),e,PasswordUtil.hash(p));c.commit();}catch(SQLException x){c.rollback();throw x;}finally{c.setAutoCommit(true);}}s.sendRedirect(r.getContextPath()+"/login.jsp?message=College+admin+registered.+Please+login.");}
 private void registerStudent(HttpServletRequest r,HttpServletResponse s)throws SQLException,IOException{String n=r.getParameter("name"),e=norm(r.getParameter("email")),p=r.getParameter("password");Integer cid=parse(r.getParameter("collegeId"));req(n,"Name is required.");req(e,"Email is required.");req(p,"Password is required.");if(p.length()<8)throw new IllegalArgumentException("Password must be at least 8 characters.");if(cid==null||!colleges.exists(cid))throw new IllegalArgumentException("Please select a valid college.");users.createPendingStudent(cid,n.trim(),e,PasswordUtil.hash(p));s.sendRedirect(r.getContextPath()+"/login.jsp?message=Student+registration+submitted.+Wait+for+admin+approval.");}
 private void registerSupervisor(HttpServletRequest r,HttpServletResponse s)throws SQLException,IOException{String n=r.getParameter("name"),e=norm(r.getParameter("email")),p=r.getParameter("password");Integer cid=parse(r.getParameter("collegeId")),courseId=parse(r.getParameter("courseId"));req(n,"Name is required.");req(e,"Email is required.");req(p,"Password is required.");if(p.length()<8)throw new IllegalArgumentException("Password must be at least 8 characters.");if(cid==null||!colleges.exists(cid))throw new IllegalArgumentException("Please select a valid college.");if(courseId==null||courses.findForCollege(courseId,cid)==null)throw new IllegalArgumentException("Please select a valid course for the selected college.");users.createPendingSupervisor(cid,courseId,n.trim(),e,PasswordUtil.hash(p));s.sendRedirect(r.getContextPath()+"/login.jsp?message=Supervisor+registration+submitted.+Wait+for+admin+approval.");}
 private void approval(HttpServletRequest r,HttpServletResponse s)throws SQLException,IOException{int collegeId=(int)r.getSession().getAttribute("collegeId"),uid=Integer.parseInt(r.getParameter("userId"));users.updateApproval(uid,collegeId,r.getParameter("status"));WebUtil.setFlash(r.getSession(),"success","Account status updated.");s.sendRedirect(r.getContextPath()+"/admin/pending");}
 private static String norm(String x){return x==null?null:x.trim().toLowerCase();}private static Integer parse(String x){try{return x==null?null:Integer.valueOf(x);}catch(Exception e){return null;}}private static void req(Object x,String m){if(x==null||x.toString().isBlank())throw new IllegalArgumentException(m);}private static String friendly(SQLException e){return e.getMessage()!=null&&e.getMessage().toLowerCase().contains("duplicate")?"That email, college, course code, or course name already exists.":e.getMessage();}
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws IOException{s.sendRedirect(r.getContextPath()+"/login.jsp");}
}
