package com.notesshared.servlet;
import com.notesshared.dao.*;import com.notesshared.model.Material;import com.notesshared.util.*;import jakarta.servlet.*;import jakarta.servlet.annotation.*;import jakarta.servlet.http.*;import java.io.*;import java.nio.file.*;import java.util.*;
@WebServlet({"/student/dashboard","/student/upload","/student/rate","/supervisor/dashboard","/supervisor/delete"})
@MultipartConfig(fileSizeThreshold=1024*1024,maxFileSize=15L*1024*1024,maxRequestSize=17L*1024*1024)
public class MaterialServlet extends HttpServlet{private final MaterialDao materials=new MaterialDao();private final CourseDao courses=new CourseDao();private final RatingDao ratings=new RatingDao();
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{try{int collegeId=(int)r.getSession().getAttribute("collegeId");switch(r.getServletPath()){case "/student/dashboard"->{Integer courseId=WebUtil.intParam(r,"courseId");String type=type(r.getParameter("type")),sort=sort(r.getParameter("sort"));r.setAttribute("materials",materials.findVisible(collegeId,courseId,type,sort));r.setAttribute("courses",courses.findByCollege(collegeId));r.setAttribute("selectedCourseId",courseId);r.setAttribute("selectedType",type);r.setAttribute("selectedSort",sort);r.getRequestDispatcher("/WEB-INF/student/dashboard.jsp").forward(r,s);}case "/student/upload"->{r.setAttribute("courses",courses.findByCollege(collegeId));r.getRequestDispatcher("/WEB-INF/student/upload.jsp").forward(r,s);}case "/supervisor/dashboard"->{int courseId=(int)r.getSession().getAttribute("courseId");r.setAttribute("course",courses.findForCollege(courseId,collegeId));r.setAttribute("materials",materials.findVisible(collegeId,courseId,"ALL","RECENT"));r.getRequestDispatcher("/WEB-INF/supervisor/dashboard.jsp").forward(r,s);}default->s.sendError(404);}}catch(Exception e){throw new ServletException(e);}}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{try{int cid=(int)r.getSession().getAttribute("collegeId"),uid=(int)r.getSession().getAttribute("userId");switch(r.getServletPath()){case "/student/upload"->upload(r,s,cid,uid);case "/student/rate"->rate(r,s,cid,uid);case "/supervisor/delete"->delete(r,s,cid,(int)r.getSession().getAttribute("courseId"));default->s.sendError(404);}}catch(Exception e){r.setAttribute("error",e.getMessage());r.getRequestDispatcher("/error.jsp").forward(r,s);}}
 private void upload(HttpServletRequest r,HttpServletResponse s,int cid,int uid)throws Exception{int courseId=Integer.parseInt(r.getParameter("courseId"));String title=r.getParameter("title"),desc=r.getParameter("description"),t=type(r.getParameter("type"));if(title==null||title.isBlank()||!Set.of("PDF","PPT","QUESTION_PAPER","NOTES").contains(t))throw new IllegalArgumentException("Title and a valid material type are required.");if(courses.findForCollege(courseId,cid)==null)throw new IllegalArgumentException("Invalid course.");Part part=r.getPart("file");if(part==null)throw new IllegalArgumentException("Please choose a PDF.");UploadUtil.validatePdf(part.getSubmittedFileName(),part.getSize());UploadUtil.SavedFile saved;try(InputStream in=part.getInputStream()){saved=UploadUtil.save(in,part.getSubmittedFileName());}try{materials.insert(cid,courseId,uid,title.trim(),desc==null?null:desc.trim(),t,part.getSubmittedFileName(),saved.storedName(),"application/pdf",part.getSize());}catch(Exception e){Files.deleteIfExists(saved.path());throw e;}WebUtil.setFlash(r.getSession(),"success","Material uploaded successfully.");s.sendRedirect(r.getContextPath()+"/student/dashboard");}
 private void rate(HttpServletRequest r,HttpServletResponse s,int cid,int uid)throws Exception{int mid=Integer.parseInt(r.getParameter("materialId")),rating=Integer.parseInt(r.getParameter("rating"));if(rating<1||rating>5)throw new IllegalArgumentException("Rating must be between 1 and 5.");if(materials.findVisibleById(mid,cid)==null)throw new IllegalArgumentException("Material not found.");ratings.upsert(mid,uid,rating);WebUtil.setFlash(r.getSession(),"success","Your rating was saved.");s.sendRedirect(r.getContextPath()+"/student/dashboard");}
 private void delete(HttpServletRequest r,HttpServletResponse s,int cid,int courseId)throws Exception{int mid=Integer.parseInt(r.getParameter("materialId"));if(!materials.belongsToSupervisorCourse(mid,cid,courseId))throw new IllegalArgumentException("Material is not part of your course.");Material m=materials.findVisibleById(mid,cid);materials.delete(mid,cid,courseId);if(m!=null)try{Files.deleteIfExists(UploadUtil.uploadDirectory().resolve(m.getStoredFilename()).normalize());}catch(Exception ignored){}WebUtil.setFlash(r.getSession(),"success","Material deleted.");s.sendRedirect(r.getContextPath()+"/supervisor/dashboard");}
 private String type(String x){return x==null||x.isBlank()?"ALL":Set.of("ALL","PDF","PPT","QUESTION_PAPER","NOTES").contains(x)?x:"ALL";}private String sort(String x){return x!=null&&Set.of("OLDEST","RATING").contains(x)?x:"RECENT";}}
