package com.notesshared.dao;
import com.notesshared.model.Course;import com.notesshared.util.Db;import java.sql.*;import java.util.*;
public class CourseDao{
 public List<Course> findByCollege(int collegeId)throws SQLException{String q="SELECT id,college_id,code,name,semester_count FROM courses WHERE college_id=? ORDER BY name";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,collegeId);try(ResultSet r=p.executeQuery()){List<Course> o=new ArrayList<>();while(r.next())o.add(read(r));return o;}}}
 public Course findForCollege(int courseId,int collegeId)throws SQLException{String q="SELECT id,college_id,code,name,semester_count FROM courses WHERE id=? AND college_id=?";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,courseId);p.setInt(2,collegeId);try(ResultSet r=p.executeQuery()){return r.next()?read(r):null;}}}
 public int createWithStructure(int collegeId,String code,String name,int semesters,List<List<String>> subjects)throws SQLException{try(Connection c=Db.getConnection()){c.setAutoCommit(false);try{int courseId;try(PreparedStatement p=c.prepareStatement("INSERT INTO courses(college_id,code,name,semester_count) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,collegeId);p.setString(2,code);p.setString(3,name);p.setInt(4,semesters);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();courseId=r.getInt(1);}}
 for(int s=1;s<=semesters;s++){int sid;try(PreparedStatement p=c.prepareStatement("INSERT INTO semesters(course_id,semester_number) VALUES(?,?)",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,courseId);p.setInt(2,s);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();sid=r.getInt(1);}}for(String sub:subjects.get(s-1)){try(PreparedStatement p=c.prepareStatement("INSERT INTO subjects(semester_id,name) VALUES(?,?)")){p.setInt(1,sid);p.setString(2,sub);p.executeUpdate();}}}c.commit();return courseId;}catch(SQLException e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}}
 private Course read(ResultSet r)throws SQLException{Course c=new Course();c.setId(r.getInt("id"));c.setCollegeId(r.getInt("college_id"));c.setCode(r.getString("code"));c.setName(r.getString("name"));c.setSemesterCount(r.getInt("semester_count"));return c;}
}
