package com.notesshared.dao;
import com.notesshared.model.Material;import com.notesshared.util.Db;import java.sql.*;import java.util.*;
public class MaterialDao{
 public void insert(int collegeId,int courseId,int uploaderId,String title,String desc,String type,String original,String stored,String content,long size)throws SQLException{String q="INSERT INTO materials(college_id,course_id,uploaded_by,title,description,material_type,original_filename,stored_filename,content_type,file_size) VALUES(?,?,?,?,?,?,?,?,?,?)";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,collegeId);p.setInt(2,courseId);p.setInt(3,uploaderId);p.setString(4,title);p.setString(5,desc);p.setString(6,type);p.setString(7,original);p.setString(8,stored);p.setString(9,content);p.setLong(10,size);p.executeUpdate();}}
 public List<Material> findVisible(int collegeId,Integer courseId,String type,String sort)throws SQLException{StringBuilder q=new StringBuilder("SELECT m.*,c.name course_name,u.name uploader_name,COALESCE((SELECT AVG(r.rating) FROM ratings r WHERE r.material_id=m.id),0) avg_rating,(SELECT COUNT(*) FROM ratings r2 WHERE r2.material_id=m.id) rating_count FROM materials m JOIN courses c ON c.id=m.course_id JOIN users u ON u.id=m.uploaded_by WHERE m.college_id=?");List<Object>ps=new ArrayList<>();ps.add(collegeId);if(courseId!=null){q.append(" AND m.course_id=?");ps.add(courseId);}if(type!=null&&!type.equals("ALL")){q.append(" AND m.material_type=?");ps.add(type);}q.append(sort.equals("OLDEST")?" ORDER BY m.created_at ASC":sort.equals("RATING")?" ORDER BY avg_rating DESC,m.created_at DESC":" ORDER BY m.created_at DESC");try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q.toString())){for(int i=0;i<ps.size();i++)p.setObject(i+1,ps.get(i));try(ResultSet r=p.executeQuery()){List<Material>o=new ArrayList<>();while(r.next())o.add(read(r));return o;}}}
 public Material findVisibleById(int id,int collegeId)throws SQLException{String q="SELECT m.*,c.name course_name,u.name uploader_name,COALESCE((SELECT AVG(r.rating) FROM ratings r WHERE r.material_id=m.id),0) avg_rating,(SELECT COUNT(*) FROM ratings r2 WHERE r2.material_id=m.id) rating_count FROM materials m JOIN courses c ON c.id=m.course_id JOIN users u ON u.id=m.uploaded_by WHERE m.id=? AND m.college_id=?";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);p.setInt(2,collegeId);try(ResultSet r=p.executeQuery()){return r.next()?read(r):null;}}}
 public boolean belongsToSupervisorCourse(int id,int collegeId,int courseId)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("SELECT 1 FROM materials WHERE id=? AND college_id=? AND course_id=?")){p.setInt(1,id);p.setInt(2,collegeId);p.setInt(3,courseId);try(ResultSet r=p.executeQuery()){return r.next();}}}
 public void delete(int id,int collegeId,int courseId)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM materials WHERE id=? AND college_id=? AND course_id=?")){p.setInt(1,id);p.setInt(2,collegeId);p.setInt(3,courseId);p.executeUpdate();}}
 private Material read(ResultSet r)throws SQLException{Material m=new Material();m.setId(r.getInt("id"));m.setCollegeId(r.getInt("college_id"));m.setCourseId(r.getInt("course_id"));m.setCourseName(r.getString("course_name"));m.setUploadedBy(r.getInt("uploaded_by"));m.setUploaderName(r.getString("uploader_name"));m.setTitle(r.getString("title"));m.setDescription(r.getString("description"));m.setMaterialType(r.getString("material_type"));m.setOriginalFilename(r.getString("original_filename"));m.setStoredFilename(r.getString("stored_filename"));m.setContentType(r.getString("content_type"));m.setFileSize(r.getLong("file_size"));m.setCreatedAt(r.getTimestamp("created_at"));m.setAverageRating(r.getDouble("avg_rating"));m.setRatingCount(r.getInt("rating_count"));return m;}
}
