package com.notesshared.dao;
import com.notesshared.model.User;import com.notesshared.util.Db;import java.sql.*;import java.util.*;
public class UserDao{
 public User findByEmail(String email)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("SELECT id,college_id,course_id,name,email,password_hash,role,approval_status FROM users WHERE email=?")){p.setString(1,email);try(ResultSet r=p.executeQuery()){return r.next()?read(r):null;}}}
 public int createAdmin(Connection c,int collegeId,String name,String email,String hash)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO users(college_id,name,email,password_hash,role,approval_status) VALUES(?,?,?,?, 'ADMIN','APPROVED')",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,collegeId);p.setString(2,name);p.setString(3,email);p.setString(4,hash);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();return r.getInt(1);}}}
 public void createPendingStudent(int collegeId,String name,String email,String hash)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO users(college_id,name,email,password_hash,role,approval_status) VALUES(?,?,?,?, 'STUDENT','PENDING')")){p.setInt(1,collegeId);p.setString(2,name);p.setString(3,email);p.setString(4,hash);p.executeUpdate();}}
 public void createPendingSupervisor(int collegeId,int courseId,String name,String email,String hash)throws SQLException{String q="INSERT INTO users(college_id,course_id,name,email,password_hash,role,approval_status) VALUES(?,?,?,?,?, 'SUPERVISOR','PENDING')";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,collegeId);p.setInt(2,courseId);p.setString(3,name);p.setString(4,email);p.setString(5,hash);p.executeUpdate();}}
 public List<User> findPendingByCollege(int collegeId)throws SQLException{String q="SELECT id,college_id,course_id,name,email,password_hash,role,approval_status FROM users WHERE college_id=? AND role IN ('STUDENT','SUPERVISOR') AND approval_status='PENDING' ORDER BY created_at";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,collegeId);try(ResultSet r=p.executeQuery()){List<User>o=new ArrayList<>();while(r.next())o.add(read(r));return o;}}}
 public void updateApproval(int userId,int collegeId,String status)throws SQLException{if(!Set.of("APPROVED","REJECTED").contains(status))throw new IllegalArgumentException("Invalid status.");try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET approval_status=? WHERE id=? AND college_id=? AND role IN ('STUDENT','SUPERVISOR')")){p.setString(1,status);p.setInt(2,userId);p.setInt(3,collegeId);p.executeUpdate();}}
 private User read(ResultSet r)throws SQLException{User u=new User();u.setId(r.getInt(1));u.setCollegeId(r.getInt(2));int c=r.getInt(3);u.setCourseId(r.wasNull()?null:c);u.setName(r.getString(4));u.setEmail(r.getString(5));u.setPasswordHash(r.getString(6));u.setRole(r.getString(7));u.setApprovalStatus(r.getString(8));return u;}
}
